version: '3.5'
services:
  app:
    image: arm64v8/php:7.4.10-fpm
    volumes:
      - ../app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8180:80"
      - "4431:443"
    depends_on:
      - mysql
    networks:
      - mydancebay-network
  mysql:
    image: arm64v8/mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/database/:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - mydancebay-network
networks:
  mydancebay-network:
    external:
      name: mydancebay-network
