version: '3'

services:
  #APP PHP
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: arm64v8/php:7.4.10-fpm
    container_name: mydancebay_php
    tty: true
    restart: unless-stopped
    depends_on:
      - maridb
    environment:
      SERVICE_NAME: mydancebay
      SERVICE_TAGS: stage
    working_dir: /var/www
    volumes:
    - ./src:/var/www
    - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini

  #Database
  maridb:
    image: arm64v8/mariadb:latest
    container_name: mydancebay_mariadb
    tty: true
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - ./database/data:/var/lib/mysql/
#      - ./database/conf/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_NAME: mydancebay
      SERVICE_TAGS: stage

  #Nginx
  nginx:
#    build:
#      context: ./nginx/Dockerfile
    image: arm64v8/nginx:alpine
    container_name: mydancebay_nginx
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - app
    environment:
      SERVICE_NAME: mydancebay
      SERVICE_TAGS: stage

  #Redis
  redis:
    image: arm64v8/redis:latest
    container_name: mydancebay_redis
    tty: true
    ports:
      - '6379:6379'
    restart: unless-stopped
    environment:
      SERVICE_NAME: mydancebay
      SERVICE_TAGS: stage

  #RabbitMQ
  rabbitmq:
    image: arm64v8/rabbitmq:latest
    container_name: mydancebay_rabbitmq
    restart: unless-stopped
    tty: true
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15671:15671'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      SERVICE_NAME: mydancebay
      SERVICE_TAGS: stage
